Return values for eupdate and edistro scripts.

diff --git a/edistro b/edistro
--- a/edistro
+++ b/edistro
@@ -26,6 +26,18 @@
 #!/bin/sh
 
 ################################################################################
+# Return codes
+
+EXIT_SUCCESS=0
+EXIT_ERROR_WRONG_PARAMETERS=1
+EXIT_ERROR_CD_WORKDIR=2
+EXIT_ERROR_NO_EUPDATE=3
+EXIT_ERROR_CREATE_TGZ=4
+EXIT_ERROR_CALC_MD5=5
+EXIT_ERROR_CREATE_EPD=6
+EXIT_ERROR_CLEAN_TMP=7
+
+################################################################################
 # Init
 
 tooldir=$(pwd)
@@ -41,20 +53,20 @@ epd=$name.epd
 
 if [ $# -eq 0 ]; then
   echo "Please specify the work directory. Exiting."
-  exit
+  exit $EXIT_ERROR_WRONG_PARAMETERS
 fi
 
 echo "Changing dir to $workdir"
 cd $workdir
 if [ "$?" -ne 0 ]; then
   echo "Error: Cannot change directory to $workdir. Exiting..."
-  exit
+  exit $EXIT_ERROR_CD_WORKDIR
 fi
 
 test -d $dir
 if [ "$?" -ne 0 ]; then
   echo "Error. Directory $workdir/$dir does not exist. Exiting..."
-  exit
+  exit $EXIT_ERROR_NO_EUPDATE
 fi
 
 if [ "$2" == "--deploy" ]; then
@@ -69,30 +81,31 @@ echo "Archiving $dir to $tgz"
 tar -czf $tgz $dir
 if [ "$?" -ne 0 ]; then
   echo "Error: Archiving failed. Exiting..."
-  exit
+  exit $EXIT_ERROR_CREATE_TGZ
 fi
 
 echo "Calculating MD5 checksum for $tgz"
 md5sum -t $tgz > $md5
 if [ "$?" -ne 0 ]; then
   echo "Error: MD5 calculation failed. Exiting..."
-  exit
+  exit $EXIT_ERROR_CALC_MD5
 fi
 
 echo "Creating distribution file $epd"
 tar -czf $epd $tgz $md5
 if [ "$?" -ne 0 ]; then
   echo "Error: Distribution file creation failed. Exiting..."
-  exit
+  exit $EXIT_ERROR_CREATE_EPD
 fi
 
 echo "Removing temporary files"
 rm $tgz $md5
 if [ "$?" -ne 0 ]; then
   echo "Error: Temporary files removal failed. Exiting..."
-  exit
+  exit $EXIT_ERROR_CLEAN_TMP
 fi
 
 echo "Success. Exiting..."
+exit $EXIT_SUCCESS
 
 ################################################################################
diff --git a/eupdate b/eupdate
--- a/eupdate
+++ b/eupdate
@@ -24,6 +24,19 @@
 #!/bin/sh
 
 ################################################################################
+# Return values
+
+EXIT_SUCCESS=0
+EXIT_UPDATE_NOT_POSSIBLE=1
+EXIT_ERROR_NO_EPD_FILE=2
+EXIT_ERROR_EXTRACTING_EPD=3
+EXIT_ERROR_EXTRACTING_TGZ=4
+EXIT_ERROR_NO_MD5_FILE=5
+EXIT_ERROR_NO_TGZ_FILE=6
+EXIT_ERROR_MD5_MISMATCH=7
+EXIT_ERROR_WRONG_PARAMETERS=8
+
+################################################################################
 # Init
 
 # Destination folder
@@ -50,12 +63,12 @@ desttool=$workdir/$0
 ################################################################################
 # Functions
 
-function quit {
+function quit() {
   # Performs clenaup and quits
   if test -d $tmp; then
     rm -r $tmp
   fi
-  exit
+  exit $1
 }
 
 ################################################################################
@@ -72,16 +85,21 @@ fi
 ################################################################################
 # Extract the epd file into tmp
 
+if [ $# -eq 0 ]; then
+  echo "Error: Wrong input parameters. Exiting..."
+  exit $EXIT_ERROR_WRONG_PARAMETERS
+fi
+
 test -f $epd
 if [ "$?" -ne 0 ]; then
   echo "Error: Please specify input epd file as first argument. Exiting..."
-  quit
+  quit $EXIT_ERROR_NO_EPD_FILE
 fi
 
 tar -xzf $epd -C $tmp                                                           # Extract update to tmp
 if [ "$?" -ne 0 ]; then
   echo "Error: Extracting $epd failed. Exiting..."
-  quit
+  quit $EXIT_ERROR_EXTRACTING_EPD
 fi
 
 ################################################################################
@@ -92,19 +110,19 @@ cd $tmp
 test -f $md5
 if [ "$?" -ne 0 ]; then
   echo "Error: $md5 file not found in $epd Exiting..."
-  quit
+  quit $EXIT_ERROR_NO_MD5_FILE
 fi
 
 test -f $tgz
 if [ "$?" -ne 0 ]; then
   echo "Error: $tgz file not found in $epd Exiting..."
-  quit
+  quit $EXIT_ERROR_NO_TGZ_FILE
 fi
 
 md5sum -c --status $md5                                                         # MD5 checksum check
 if [ $? -ne 0 ]; then
   echo "Error: MD5 checksum mismatch. Exiting..."
-  quit
+  quit $EXIT_ERROR_MD5_MISMATCH
 fi
 echo "MD5 checksum OK"
 
@@ -112,7 +130,7 @@ echo "Extracting $tgz"
 tar -xzf $tgz -C $tmp                                                           # Extract update to tmp
 if [ "$?" -ne 0 ]; then
   echo "Error: Extracting $tgz failed. Exiting..."
-  quit
+  quit $EXIT_ERROR_EXTRACTING_TGZ
 fi
 
 ################################################################################
@@ -135,7 +153,7 @@ done
 
 if [ "$updatable" -eq 0 ]; then                                                 # Exit if update not possible
   echo "Update from version $cur_version to version $new_version not possible"
-  quit
+  quit $EXIT_UPDATE_NOT_POSSIBLE
 fi
 
 echo "Updating from version $cur_version to version $new_version"
@@ -188,7 +206,7 @@ if test -f $sourcetool; then
     sh $erevert
     sh $desttool $epd
 
-    quit
+    quit $EXIT_SUCCESS
   fi
 fi
 
@@ -263,4 +281,4 @@ sed -i "1i#!/bin/sh" $erevert
 ################################################################################
 # Cleanup and quit
 
-quit
+quit $EXIT_SUCCESS
